### ISSUE TITLE
dataclasses error when running examples/mnist.py with Python 3.11

### ISSUE THREAD

**Issue by chariako** [APPFL/APPFL#128]
I am using a M2 Macbook Pro and had to install mpi4py through Homebrew; however, mpi4py has a dependency on Python 3.11. 
When I run mnist.py from the examples with Python 3.11 I get the following error:

```
Traceback (most recent call last):
 File "/Users/hara/Documents/APPFL-fedasync-dev/examples/./mnist.py", line 10, in <module>
  from appfl.config import *
 File "/opt/homebrew/lib/python3.11/site-packages/appfl-0.2.1-py3.11.egg/appfl/config/__init__.py", line 3, in <module>
 File "/opt/homebrew/lib/python3.11/site-packages/appfl-0.2.1-py3.11.egg/appfl/config/config.py", line 12, in <module>
 File "/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/dataclasses.py", line 1223, in dataclass
  return wrap(cls)
      ^^^^^^^^^
File "/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/dataclasses.py", line 1213, in wrap
  return _process_class(cls, init, repr, eq, order, unsafe_hash,
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 
File "/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/dataclasses.py", line 958, in _process_class
  cls_fields.append(_get_field(cls, name, type, kw_only))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/dataclasses.py", line 815, in _get_field
  raise ValueError(f'mutable default {type(f.default)} for field '
ValueError: mutable default <class 'appfl.config.fed.federated.Federated'> for field fed is not allowed: use default_factory
```

**Comment by kibaekkim** [comment]
https://stackoverflow.com/questions/53632152/why-cant-dataclasses-have-mutable-defaults-in-their-class-attributes-declaratio

It looks like the python version is sensitive to a certain way of using `@dataclass`. We are using this in a few files. We may need to update the code to be compatible to python 3.11.

**Comment by yim0331** [comment]
This issue is addressed by the [PR 132](https://github.com/APPFL/APPFL/pull/132)
