### ISSUE TITLE
mpi4py High-level recv() Causes Crash on NCSA Delta Inter-node Communication  in mpi_communicator.py

### ISSUE THREAD

**Issue by ben072292** [APPFL/APPFL#191]
**Description:**
I encountered an issue when running APPFL examples in distributed memory environments involving MPI communication, specifically when invoking functions in mpi_communicator.py on **NCSA Delta with inter-node communication**. The problem appears to be related to the use of mpi4py’s high-level recv() method, which causes a crash. Here are the details:

**Environment:**
- **System:** NCSA Delta
- **GCC Version:** GCC-11.4.0 (Default)
- **MPI Version:** OpenMPI-4.1.6 (Default)
- **mpi4py Version:** 3.1.6 (Latest version as of writing)
- **Python Version:** 3.8.19 (Recommended by APPFL)
- **APPFL Version:** 0.4.2 (Latest version as of writing)

**Error Message:**
```
======================   ALLOCATED NODES   ======================
        cn063: flags=0x10 slots=1 max_slots=0 slots_inuse=0 state=UP
        cn064: flags=0x10 slots=1 max_slots=0 slots_inuse=0 state=UP
=================================================================
Rank 0 prepared data: {'done': False}
Rank 0 sent data: {'done': False}
Traceback (most recent call last):
  File "/u/wchen2/PDES/mpi4py_send_recv_fail.py", line 14, in <module>
    data = comm.recv(source=0, tag=11)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "mpi4py/MPI/Comm.pyx", line 1438, in mpi4py.MPI.Comm.recv
  File "mpi4py/MPI/msgpickle.pxi", line 340, in mpi4py.MPI.PyMPI_recv
  File "mpi4py/MPI/msgpickle.pxi", line 302, in mpi4py.MPI.PyMPI_recv_match
mpi4py.MPI.Exception: MPI_ERR_OTHER: known error not in list
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpiexec detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[14239,1],1]
  Exit code:    1
```

**Steps to Reproduce:**
1. Allocate 2 nodes on NCSA Delta.
2. Run the following script (simplified example that mimics the issue):

    ```python
    from mpi4py import MPI

    comm = MPI.COMM_WORLD
    rank = comm.Get_rank()

    if rank == 0:
        data = {'done': False} ## not has to be a dict, simple int would crash too
        print(f"Rank {rank} prepared data: {data}")
        comm.send(data, dest=1, tag=11)
        print(f"Rank {rank} sent data: {data}")

    elif rank == 1:
        data = comm.recv(source=0, tag=11)
        print(f"Rank {rank} received data: {data}")
    ```

3. Observe the crash on Rank 1 with the error message mentioned above.

**Possible Cause:**
The issue might be related to how `mpi4py`'s high-level `recv()` handles the serialization/deserialization of the data or the specific MPI implementation on NCSA Delta.

**Suggested Solution:**
Consider using the low-level API for `mpi4py`'s send and receive operations (i.e., Send() and Recv() with explicit buffer handling), which has been personally verified to circumvent the issue with the high-level API. 

**Additional Information:**
- Intra-node communication doesn't pose the above issues.
- The send()/recv() calls in mpi_communicator.py are predominantly used for communicating a combination of metadata and control messages with different data types, such as lists containing an integer of model size and dictionaries of additional arguments (e.g., [1024, {"done": False}]).
- I have a working version of mpi_communicator.py that replaces all send()/recv() calls with Send()/Recv() and handles data (de)serialization and buffer management explicitly. I can create a pull request if this solution is acceptable to you.

**Example of a Low-Level API Workaround:**
```python
from mpi4py import MPI
import pickle
import numpy as np

comm = MPI.COMM_WORLD
rank = comm.Get_rank()

if rank == 0:
    data = {"done": False}
    serialized_data = pickle.dumps(data)
    data_size = len(serialized_data)
    comm.Send(np.array([data_size], dtype=np.int32), dest=1, tag=11)
    comm.Send([np.frombuffer(serialized_data, dtype=np.byte), MPI.BYTE], dest=1, tag=12)
    print(f"Rank {rank} sent data: {data}")

elif rank == 1:
    size_buffer = np.empty(1, dtype=np.int32)
    comm.Recv(size_buffer, source=0, tag=11)
    data_size = size_buffer[0]
    recv_buf = np.empty(data_size, dtype=np.byte)
    comm.Recv(recv_buf, source=0, tag=12)
    data = pickle.loads(recv_buf.tobytes())
    print(f"Rank {rank} received data: {data}")
```

I hope this description helps in diagnosing and fixing the issue. Thank you for your attention to this matter.

Best,
Ben

**Comment by ben072292** [comment]
Closed this issue as resolved since v1.0.0
