### ISSUE TITLE
Runtime error from serial run on single GPU

### ISSUE THREAD

**Issue by kibaekkim** [APPFL/APPFL#40]
Parallel runs with MPI work well. This is because the implementation assumes that the server is running on CPU only regardless of which architecture clients run on. However, in serial run the server can run on GPU, by which the server potentially uses memory on both CPU and GPU.

```
----------Loaded Datasets and Model----------Elapsed Time= 15.384193420410156
        Iter     Local[s]    Global[s]     Valid[s]      Iter[s]   Elapsed[s]  TestAvgLoss TestAccuracy     Prim_res     Dual_res    Penal_min    Penal_max
Traceback (most recent call last):
  File "mnist.py", line 117, in <module>
    main()
  File "mnist.py", line 113, in main
    rt.run_serial(cfg, model, train_datasets, test_dataset, DataSet_name)
  File "/home/kimk/.conda/envs/appfl-release-test/lib/python3.8/site-packages/appfl/run.py", line 108, in run_serial
    prim_res, dual_res, rho_min, rho_max = server.update(local_states)
  File "/home/kimk/.conda/envs/appfl-release-test/lib/python3.8/site-packages/appfl/algorithm/fedavg.py", line 27, in update
    prim_res = super(FedAvgServer, self).primal_residual_at_server(global_state)
  File "/home/kimk/.conda/envs/appfl-release-test/lib/python3.8/site-packages/appfl/algorithm/algorithm.py", line 78, in primal_residual_at_server
    global_state[name] - self.primal_states[i][name].to(self.device)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
```

**Comment by kibaekkim** [comment]
@minseok-ryu I still get the same error on linux with cuda. I ran `mnist.py` below

```shell
mpiexec -np 3 python mnist.py
```

with the following modifications:

```
diff --git a/examples/mnist.py b/examples/mnist.py
index a705d92..c13cdd8 100644
--- a/examples/mnist.py
+++ b/examples/mnist.py
@@ -15,7 +15,7 @@ import appfl.run as rt
 from mpi4py import MPI

 DataSet_name = "MNIST"
-num_clients = 4
+num_clients = 2
 num_channel = 1  # 1 if gray, 3 if color
 num_classes = 10  # number of the image classes
 num_pixel = 28  # image size = (num_pixel, num_pixel)
@@ -101,6 +101,7 @@ def main():

     # read default configuration
     cfg = OmegaConf.structured(Config)
+    cfg.device = "cuda"

     if comm_size > 1:
         if comm_rank == 0:
```

**Comment by kibaekkim** [comment]
I think the package was not properly installed...
