### ISSUE TITLE
Revise ``run_grpc_client.py`` 

### ISSUE THREAD

**Issue by minseok-ryu** [APPFL/APPFL#67]
**[Issue]** 
For the federated learning with 2 GPU clients (``run_grpc_client.py``), the client 2 (client_id=2) experiences the following error:
```
Traceback (most recent call last):
  File "deepcovid_binary_class_1_client.py", line 100, in <module>
    main()
  File "deepcovid_binary_class_1_client.py", line 94, in main
    grpc_client.run_client(cfg, args.client_id, model, train_dataset)
  File "/home/mryu/.conda/envs/APPFLClient/lib/python3.8/site-packages/appfl/run_grpc_client.py", line 108, in run_client
    local_state = fed_client.update()
  File "/home/mryu/.conda/envs/APPFLClient/lib/python3.8/site-packages/appfl/algorithm/fedavg.py", line 57, in update
    self.model.to(self.device)
  File "/home/mryu/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 899, in to
    return self._apply(convert)
  File "/home/mryu/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 570, in _apply
    module._apply(fn)
  File "/home/mryu/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 593, in _apply
    param_applied = fn(param)
  File "/home/mryu/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 897, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
RuntimeError: CUDA error: invalid device ordinal
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
```

The reason for this error is described in https://programmerah.com/solved-runtimeerror-cuda-error-invalid-device-ordinal-36817/

**[Solution]**
Revise the following code:

```python
def run_client(cfg        : DictConfig,
               comm_rank  : int,
               model      : nn.Module,
               train_data : Dataset) -> None:
    """Launch gRPC client to connect to the server specified in the configuration.

    Args:
        cfg (DictConfig): the configuration for this run
        comm_rank (int): MPI rank
        model (nn.Module): neural network model to train
        train_data (Dataset): training data
    """

    logger = logging.getLogger(__name__)
    if cfg.server.use_tls == True:
        uri = cfg.server.host
    else:
        uri = cfg.server.host + ':' + str(cfg.server.port)

    cid = comm_rank - 1

    ## We assume to have as many GPUs as the number of MPI processes.
    if cfg.device == "cuda":
        device = f"cuda:{cid}"
    else:
        device = cfg.device
```

**Comment by youngdae** [comment]
How about replacing `comm_rank` with `cid` and having an additional argument `gpu_id`, which is set to `0` by default?

**Comment by minseok-ryu** [comment]
def run_client(cfg        : DictConfig,
               cid  : int,
               model      : nn.Module,
               train_data : Dataset) -> None:
    """Launch gRPC client to connect to the server specified in the configuration.

    Args:
        cfg (DictConfig): the configuration for this run
        cid (int): client id (starting from 0)
        gpu_id (int): client id (starting from 0)
        model (nn.Module): neural network model to train
        train_data (Dataset): training data
    """

    logger = logging.getLogger(__name__)
    if cfg.server.use_tls == True:
        uri = cfg.server.host
    else:
        uri = cfg.server.host + ':' + str(cfg.server.port)



    ## We assume to have as many GPUs as the number of MPI processes.
    if cfg.device == "cuda":
        device = f"cuda:{gpu_id}"
    else:
        device = cfg.device

**Comment by youngdae** [comment]
Would this work?

```python
def run_client(cfg        : DictConfig,
               cid  : int,
               model      : nn.Module,
               train_data : Dataset,
               gpu_id : int = 0) -> None:
    """Launch gRPC client to connect to the server specified in the configuration.

    Args:
        cfg (DictConfig): the configuration for this run
        cid (int): client id (starting from 0)
        model (nn.Module): neural network model to train
        train_data (Dataset): training data
        gpu_id (int): client id (starting from 0)
    """

    logger = logging.getLogger(__name__)
    if cfg.server.use_tls == True:
        uri = cfg.server.host
    else:
        uri = cfg.server.host + ':' + str(cfg.server.port)



    ## We assume to have as many GPUs as the number of MPI processes.
    if cfg.device == "cuda":
        device = f"cuda:{gpu_id}"
    else:
        device = cfg.device
```

**Comment by minseok-ryu** [comment]
If gpu_id = 1, then device is set to be "cuda:1" ?

**Comment by youngdae** [comment]
Yes. In that case, there should be more than one CUDA device on the machine. Otherwise, it will generate an error like you had.

**Comment by minseok-ryu** [comment]
Thank you
